# This workflow will build and push a Docker image for the Golang project

name: Go Docker Build and Push

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout repository
    - uses: actions/checkout@v4

    # Login to Docker Hub
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    # Build and push Docker image
    - name: Build and push Docker image
      uses: docker/build-push-action@v6
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ganangsetyohadi/praktikum-popl-5:latest

    # Optional: Test Docker container
    - name: Run Docker container and test
      run: |
        docker run -d -p 8080:8080 ganangsetyohadi/praktikum-popl-5:latest
        sleep 10 # Tunggu container berjalan
        curl --fail http://localhost:8080 || exit 1
